Added support for updating post status.
gravitywiz/snippet-library pull request #105
Opened 2021-06-11 15:18 UTC by scyt

The idea for this is a choice field with the different post status as available choices.

![](https://gwiz.media/grabs/2021-06-11_11-17-09.png)

This choice field can be populated via GPPA:

![](https://gwiz.media/grabs/2021-06-11_11-17-41.png)

2021-06-12 01:10 UTC, spivurno requested changes
I dig it! Great summary as well. Just one reliability note below.

2021-06-12 01:10 UTC, spivurno commented on gravity-forms/gw-update-posts.php
> +		}
It'd be awesome if we could get a list of [registered post statuses](https://developer.wordpress.org/reference/functions/get_post_stati/) and then make sure that the user-selected (or enetered) status is a valid post status before we attempt to set it. If not, we could just skip updating it.

2021-06-14 13:50 UTC, scyt commented
Good call. I added a check to see if the post status exists. If it doesn't, it skips updating.

2021-06-14 19:14 UTC, spivurno approved these changes
Perfect!

2021-06-14 19:49 UTC, merged