Copy Product Value Without the Price
gravitywiz/snippet-library pull request #146
Opened 2021-09-09 03:00 UTC by sbassah

Original Gist: https://gist.github.com/spivurno/d3ddce62882808d6dae177c3a528e2f1

2021-09-09 13:32 UTC, spivurno commented on gp-copy-cat/gpcc-copy-product-value.js
> +* Copy the value of a choice based product field without the price.
Update to:
> By default, choice-based Product fields will copy a raw value that includes both the selected value and the price of the selection option(s). Use this snippet to copy only the value and exclude the price.

2021-09-09 13:33 UTC, spivurno commented on gp-copy-cat/gpcc-copy-product-value.js
> +* 3. Update the target field ID within the snippet.
Can we update these instructions to use our [Custom Javascript](https://gravitywiz.com/gravity-forms-custom-javascript/) plugin instead?

2021-09-09 13:34 UTC, spivurno requested changes

2021-09-09 13:34 UTC, spivurno commented on gp-copy-cat/gpcc-copy-product-value.js
> +<script type="text/javascript">
Ditch these since we'll be using our Custom Javascript plugin.

2021-09-09 13:34 UTC, spivurno commented on gp-copy-cat/gpcc-copy-product-value.js
> +</script>
Ditch this one too.

2021-09-09 17:34 UTC, sbassah commented
I have made the changes requested.

2021-09-10 12:56 UTC, spivurno approved these changes

2021-09-10 15:47 UTC, merged