Update gpwc-disable-truncation.php
gravitywiz/snippet-library pull request #457
Opened 2022-08-01 17:29 UTC by dariospace

added instruction video

2022-08-16 19:19 UTC, scyt requested changes
This one is good, but the volume is pretty low. Is there any way to increase the volume in Loom without having to re-record?

2022-08-24 20:05 UTC, dariospace commented
@scyt I've added a new video to the snippet with improved sound

2022-09-08 18:00 UTC, scyt requested changes
I hate to make you record this one again, but the aspect ratio is off. Can you redo this one with only the window being captured?

2022-09-16 17:57 UTC, scyt approved these changes

2022-09-19 18:40 UTC, merged