`gppa-populate-checkboxes-as-choices.php`: Added Instruction Video and Updated Snippet Header.
gravitywiz/snippet-library pull request #521
Opened 2022-09-13 14:11 UTC by levisimon

## Summary
`gppa-populate-checkboxes-as-choices.php`: Added Instruction Video and Updated Snippet Header.

2022-09-20 20:57 UTC, scyt requested changes
I think the best demo for this is to populate into a Radio Buttons or a Drop Down field. Populating into a checkbox works, but in my experience most users are populating into another choice type.

I'm also curious about changing FORMID and FIELDID to 123 and 4. Tagging @spivurno for his input there.

2022-09-21 15:00 UTC, spivurno commented
Using "123" and "4" for form ID and field ID is our current practice. All good there!

2022-09-21 15:00 UTC, spivurno approved these changes

2022-11-08 15:34 UTC, dariospace commented
@scyt should we approve this one? I'm not sure what would be the next step in the Workflow

2022-11-08 15:42 UTC, scyt commented
@dariospace Could you record a new version where you populate into a Radio Buttons field? That better matches the use case of this snippet.

Also, make sure to use the new template for the commit message. You'll also need to edit the PR name.

2025-01-10 11:59 UTC, closed without merging