Spots Left + Waiting List Message
gravitywiz/snippet-library pull request #68
Opened 2021-04-05 16:32 UTC by sbassah

Original Gist: https://gist.github.com/spivurno/82092c812c49891670dc

2021-04-07 23:08 UTC, spivurno requested changes
1. This is missing an opening <?php tag.
2. Some of the code here appears to be out-of-date. Can you take a look at how the limit and how many left are calculated in [this snippet](https://github.com/gravitywiz/snippet-library/blob/master/gp-limit-choices/gplc-spots-left.php) and use that here?

2021-04-08 17:28 UTC, sbassah commented
I have made the changes requested, please.

2021-04-10 22:10 UTC, spivurno approved these changes
Approved pending two minor verbiage tweaks. ✅

2021-04-10 22:10 UTC, spivurno commented on gp-limit-choices/gplc-spots-left-plus-waiting-list.php
> + * Plugin URI:   https://gravitywiz.com/documentation/gp-limit-choices/
Let's update this URL to "https://gravitywiz.com/documentation/gravity-forms-limit-choices/"

2021-04-10 22:10 UTC, spivurno commented on gp-limit-choices/gplc-spots-left-plus-waiting-list.php
> + * Description:  This snippet allows you to display the number of spots left in the label of each choice. If there are no spots left, it will display a waiting list message.
Let's drop "This snippet allows you to " from the plugin description.

2021-04-12 15:10 UTC, merged