`gpep-edit-entry.php`: Added support for workflow restarting when an entry is edited on the frontend with GPEPEE.
gravitywiz/snippet-library pull request #711
Opened 2023-09-27 11:25 UTC by saifsultanc

## Context

⛑️ Ticket(s): https://secure.helpscout.net/conversation/2359338748/54671?folderId=3808239

## Summary

With the snippet [Edit Entries via Easy Passthrough](https://gravitywiz.com/edit-gravity-forms-entries-on-the-front-end/) snippet, Gravity Flow Workflow is not restarted. This update adds an option for that functionality.

2023-09-27 13:22 UTC, spivurno commented
Looking good, @saifsultanc!

We'll also want to set this new option around here for clarity about which options are accepted:

https://github.com/gravitywiz/snippet-library/blob/29a724f75cec4edca130538adb7175e40c3ee4a0/gp-easy-passthrough/gpep-edit-entry.php#L29

2023-09-27 13:56 UTC, saifsultanc commented
> $this->refresh_token = rgar( $options, 'refresh_token', false );

Yikes. Forgot this final push!

2023-09-27 14:32 UTC, claygriffiths requested changes
Looking good! I have a few suggestions.

`workflow` is a bit generic in some places such as the comments and PR title so I'd update it to `Gravity Flow workflow`. I think `restart_workflow` is fine for a parameter name, however.

2023-09-27 14:32 UTC, claygriffiths commented on gp-easy-passthrough/gpep-edit-entry.php
> +	'restart_workflow' => true,  // Set this to true to restart the workflow.
```suggestion
	'restart_workflow' => true,  // Set this to true to restart the Gravity Flow workflow.
```

2023-09-27 14:32 UTC, claygriffiths commented on gp-easy-passthrough/gpep-edit-entry.php
> +			if ( $this->restart_workflow ) {
```suggestion
			if ( $this->restart_workflow && class_exists( 'Gravity_Flow_API' ) ) {
```

2023-09-28 10:42 UTC, saifsultanc commented
> Looking good! I have a few suggestions.
> 
> `workflow` is a bit generic in some places such as the comments and PR title so I'd update it to `Gravity Flow workflow`. I think `restart_workflow` is fine for a parameter name, however.

Ready for re-review. PHPCS points to issues which are not part of this PR.

2023-09-28 15:58 UTC, claygriffiths approved these changes
LGTM! One final tweak requested.

2023-09-28 15:58 UTC, claygriffiths commented on gp-easy-passthrough/gpep-edit-entry.php
> +	'restart_workflow' => true,  // Set this to true to restart the Gravity Flow workflow.
I'd default this to `false`.

2025-01-15 06:53 UTC, saifsultanc commented
Closing because of the conflict right now, and we have already added an option for processing feeds - feeds can be defined.. so `gravityflow` can be defined with that.

2025-01-15 06:53 UTC, closed without merging