`gpnf-delay-child-notifications-for-parent-payment.php`: Send notification if no payment status for parent entry.
gravitywiz/snippet-library pull request #976
Opened 2024-12-30 13:12 UTC by malayladu

## Context

This PR allows to send notification instantly even if parent entry doesn't have payment status.

⛑️ Ticket(s): https://secure.helpscout.net/conversation/2794049850/75576

## Summary

Delay notification only checks for the payment status of parent entry `Paid` & `Active`. But, it doesn't send notification if there is no payment status for the parent entry.

So, this fix checks whether the payment status is available or not. If not, it allows to send notification.

2024-12-31 05:56 UTC, saifsultanc requested changes

2024-12-31 05:56 UTC, saifsultanc commented on gp-nested-forms/gpnf-delay-child-notifications-for-parent-payment.php
> +			$payment_status = rgar( $parent_entry, 'payment_status', '' );
Can we simplify the change, like-

```php
$should_send_notification = in_array( rgar( $parent_entry, 'payment_status' ), array( '', 'Paid', 'Active' ), true );
```

Were you able to verify David's concern? "Due to order of events, will there be a point where all parent entries (even those that will eventually have a payment status) come through this code before they have a payment status?"

2025-01-01 14:59 UTC, malayladu commented on gp-nested-forms/gpnf-delay-child-notifications-for-parent-payment.php
> +			$payment_status = rgar( $parent_entry, 'payment_status', '' );
No. I didn't come across to a similar situation.

2025-01-08 03:49 UTC, claygriffiths approved these changes
LGTM if everything is working as expected.

S&M with:

```
`gpnf-delay-child-notifications-for-parent-payment.php`: Updated behavior to send notifications if the parent entry does not have a payment status. This provides more flexibility with conditional logic.
```

2025-01-08 04:43 UTC, merged